docker/nginx/conf.d/default.conf

closes https://github.com/inveniosoftware/helm-invenio/issues/47

nginx: added robots.txt rule

---

invenio.cfg

auth: add SSO config

---

assets/less/cds-rdm/globals/site.overrides
templates/semantic-ui/invenio_app_rdm/frontpage.html

Info box: add links

---

assets/js/invenio_app_rdm/frontpage/override.js
assets/js/invenio_app_rdm/frontpage/overrides/RecordsList.js
assets/js/invenio_app_rdm/frontpage/overrides/RecordsResultsListItem.js
assets/less/cds-rdm/elements/image.overrides
assets/less/cds-rdm/globals/site.overrides
assets/less/cds-rdm/globals/site.variables
site/.gitkeep
site/cds_rdm/assets/semantic-ui/js/cds_rdm/.gitkeep
site/cds_rdm/assets/semantic-ui/less/cds_rdm/.gitkeep
site/cds_rdm/templates/semantic-ui/cds_rdm/.gitkeep
site/cds_rdm/views.py
site/cds_rdm/webpack.py
site/pyproject.toml
site/setup.cfg
site/setup.py
site/tests/.gitkeep
templates/semantic-ui/invenio_app_rdm/frontpage.html
templates/semantic-ui/invenio_app_rdm/macros/records_list.html
translations/babel.ini

closes: #8
Width: 3/4 Height: 9/10 of semantic ui's medium image (commited)
Width: 3/4 Height: 8/10
Width: 3/5 Height: 9/10
Width: 3/5 Height: 8/10

Frontpage: customize recent uploads [REQUIRES: inveniosoftware/invenio-app-rdm#1971]

---

assets/js/invenio_app_rdm/frontpage/overrides/RecordsResultsListItem.js
assets/less/cds-rdm/elements/image.overrides
assets/less/cds-rdm/globals/site.overrides

Frontpage: set object fit on recent upload item image

---

invenio.cfg

* enable local account registration for development purposes
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/22

disable sending account-related emails

---

assets/less/cds-rdm/globals/site.overrides
invenio.cfg
templates/cds_rdm/header.html
templates/semantic-ui/invenio_app_rdm/footer.html
templates/semantic-ui/invenio_app_rdm/frontpage.html
templates/semantic-ui/invenio_app_rdm/header.html
templates/semantic-ui/invenio_app_rdm/header_frontpage.html
templates/semantic-ui/invenio_app_rdm/macros/records_list.html

ui: add demo banner

---

assets/js/components/frontpage/overrides/RecordsResultsListItem.js
assets/less/cds-rdm/collections/grid.overrides
assets/less/cds-rdm/elements/image.overrides
assets/less/cds-rdm/globals/site.overrides
templates/semantic-ui/invenio_app_rdm/frontpage.html
templates/semantic-ui/invenio_app_rdm/header.html
templates/semantic-ui/invenio_app_rdm/header_frontpage.html

Fix recent uploads mobile UI.
Remove white border on navbar.
closes: #39
New Version:
- Computer:
- Tablet:
- Mobile:
Old Version:
- Computer:
- Tablet:
- Mobile:

Frontpage: fix header mobile UI

---

assets/js/components/frontpage/overrides/RecordsList.js
assets/js/components/frontpage/overrides/RecordsResultsListItem.js
assets/js/invenio_app_rdm/frontpage/override.js

Hide section on empty results.
closes: inveniosoftware/invenio-app-rdm#1996

Records list: refactor override to use only jsx

---

site/cds_rdm/oidc.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/61

oidc: add locale to prefs

---

Dockerfile
invenio.cfg

Dockerfile: install kstart

---

Pipfile
Pipfile.lock
invenio.cfg
site/cds_rdm/oidc.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/16

oidc: adds group handler

---

invenio.cfg
site/cds_rdm/__init__.py
site/cds_rdm/errors.py
site/cds_rdm/tasks.py
site/setup.cfg

* Note for reviewers: check only last commit
* Needs https://github.com/CERNDocumentServer/cds-rdm/pull/66
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/68

Add group sync

---

invenio.cfg
site/cds_rdm/templates/semantic-ui/invenio_notifications/email/community-submission.submit.jinja

* closes https://github.com/inveniosoftware/invenio-app-rdm/issues/2280

notifications: override community inclusion template

---

Pipfile.lock
invenio.cfg
site/cds_rdm/assets/semantic-ui/js/cds_rdm/src/records/detail.js
site/cds_rdm/ldap/api.py
site/cds_rdm/templates/semantic-ui/my_site/.gitkeep
site/cds_rdm/webpack.py
templates/cds_rdm/page.html
templates/cds_rdm/records/detail.html
templates/semantic-ui/invenio_app_rdm/records/details/doi.html

landing-page: add conceptdoi

---

invenio.cfg
site/cds_rdm/ext.py
site/cds_rdm/oidc.py

Requires: https://github.com/inveniosoftware/invenio-oauthclient/pull/315

groups: fetch async to improve login performance

---

templates/semantic-ui/invenio_app_rdm/records/detail.html

* Temporary fix to be reverted once upgraded

records: override detail template

---

assets/less/cds-rdm/collections/menu.overrides
templates/semantic-ui/invenio_app_rdm/header.html

Closes https://github.com/CERNDocumentServer/cds-rdm/issues/105

header: Add active state to menu items

---

templates/semantic-ui/invenio_app_rdm/records/details/doi.html

* needs https://github.com/inveniosoftware/invenio-app-rdm/pull/2338

[TO BE MERGED WHEN CODE UPGRADE] DOI: fix concept doi 

---

templates/semantic-ui/invenio_notifications/community-invitation.accept.jinja
templates/semantic-ui/invenio_notifications/community-invitation.cancel.jinja
templates/semantic-ui/invenio_notifications/community-invitation.decline.jinja
templates/semantic-ui/invenio_notifications/community-invitation.expire.jinja
templates/semantic-ui/invenio_notifications/community-submission.cancel.jinja
templates/semantic-ui/invenio_notifications/community-submission.decline.jinja
templates/semantic-ui/invenio_notifications/community-submission.expire.jinja
templates/semantic-ui/invenio_notifications/community-submission.submit.jinja
templates/semantic-ui/invenio_notifications/grant-user-access.create.jinja
templates/semantic-ui/invenio_notifications/guest-access-request-token.create.jinja
templates/semantic-ui/invenio_notifications/guest-access-request.accept.jinja
templates/semantic-ui/invenio_notifications/guest-access-request.cancel.jinja
templates/semantic-ui/invenio_notifications/guest-access-request.decline.jinja
templates/semantic-ui/invenio_notifications/guest-access-request.submit.jinja
templates/semantic-ui/invenio_notifications/guest-access-request.submitted.jinja
templates/semantic-ui/invenio_notifications/user-access-request.accept.jinja
templates/semantic-ui/invenio_notifications/user-access-request.cancel.jinja
templates/semantic-ui/invenio_notifications/user-access-request.decline.jinja
templates/semantic-ui/invenio_notifications/user-access-request.submit.jinja

*closes https://github.com/CERNDocumentServer/cds-rdm/issues/153

templates: add email templates

---

Dockerfile
invenio.cfg
site/cds_rdm/files.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/167

Offloading

---

invenio.cfg

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/143
* NEEDS https://github.com/inveniosoftware/invenio-app-rdm/pull/2769
* NEEDS https://github.com/inveniosoftware/react-invenio-forms/pull/248
Loaded from: https://gitlab.cern.ch/cds-team/cds-legacy/-/blob/master/src/wn-cdsweb/etc/bibconvert/KB/SISC-65017a.kb

vocab: add subjects

---

Pipfile
Pipfile.lock

To fix tests:
```
ERROR tests/test_permissions.py::test_archiver_permissions - jsonschema.exceptions._RefResolutionError: <urlopen error unknown url type: local>
```

Pipfile: Install jsonschema to fix RefReslutonError

---

docker-services.yml
invenio.cfg

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/226

config: add personorg identifiers schemes

---

app_data/vocabularies/experiments.yaml

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/170
Harvested from greybook using https://gitlab.cern.ch/cds-team/cds-legacy/blob/master/src/wn-cdsweb/bin/grey_book_experiments_synchro#L303

vocabularies: harvest latest experiments

---

templates/semantic-ui/invenio_app_rdm/header.html
templates/semantic-ui/invenio_app_rdm/header_frontpage.html

CLoses https://github.com/CERNDocumentServer/cds-rdm/issues/296

ui: move banner below the navbar

---

invenio.cfg

config: set community records search options identical to records search

---

invenio.cfg

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/256

conf: update stats to yearly

---

Pipfile
Pipfile.lock
site/cds_rdm/files.py
site/cds_rdm/schemes.py
site/setup.cfg

* the generator is expected to be callable in idutils
* see https://github.com/zenodo/zenodo-rdm/issues/1121

schemes: remove incorrect config

---

Pipfile
Pipfile.lock

* applies conditional (feature flag) signposting

installation: upgrade invenio-app-rdm

---

app_data/vocabularies.yaml
app_data/vocabularies/awards.yaml
app_data/vocabularies/programmes.yaml
assets/templates/custom_fields/CERNFields.js
invenio.cfg
site/cds_rdm/custom_fields/cern.py
site/cds_rdm/schemes.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/385
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/396

Custom identifiers

---

invenio.cfg

search: add mappings for custom fields

---

invenio.cfg

config: update OAISERVER_ID_PREFIX to repository.cern

---

invenio.cfg
site/cds_rdm/components.py
site/tests/conftest.py
site/tests/test_components.py

components: add component for system subject validation

---

assets/js/invenio_app_rdm/overridableRegistry/mapping.js

* requires https://github.com/inveniosoftware/invenio-app-rdm/pull/3067

Section cern feedback fix

---

site/cds_rdm/inspire_harvester/writer.py

* closes https://github.com/CERNDocumentServer/cds-rdm/issues/430

inspire: improve error handling on writer
